# Generated by Django 3.1.4 on 2021-12-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='user_profile',
            new_name='organization',
        ),
    ]
